const API_KEY = process.env.CRYPTO_API_KEY;

export async function GET(request: Request) {
//   const url = new URL(request.url);
//   const limit = url.searchParams.get("limit") || 5;

//   const response = await fetch(
//     `https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest?start=1&limit=${limit}&convert=EUR`,
//     {
//       headers: {
//         "X-CMC_PRO_API_KEY": API_KEY!,
//       },
//     }
//   );

//   const res = await response.json();
//   return Response.json(res.data);
  return Response.json(data);
}

const data = [
    {
        "id": 1,
        "name": "Bitcoin",
        "symbol": "BTC",
        "slug": "bitcoin",
        "num_market_pairs": 11957,
        "date_added": "2010-07-13T00:00:00.000Z",
        "tags": [
            "mineable",
            "pow",
            "sha-256",
            "store-of-value",
            "state-channel",
            "coinbase-ventures-portfolio",
            "three-arrows-capital-portfolio",
            "polychain-capital-portfolio",
            "binance-labs-portfolio",
            "blockchain-capital-portfolio",
            "boostvc-portfolio",
            "cms-holdings-portfolio",
            "dcg-portfolio",
            "dragonfly-capital-portfolio",
            "electric-capital-portfolio",
            "fabric-ventures-portfolio",
            "framework-ventures-portfolio",
            "galaxy-digital-portfolio",
            "huobi-capital-portfolio",
            "alameda-research-portfolio",
            "a16z-portfolio",
            "1confirmation-portfolio",
            "winklevoss-capital-portfolio",
            "usv-portfolio",
            "placeholder-ventures-portfolio",
            "pantera-capital-portfolio",
            "multicoin-capital-portfolio",
            "paradigm-portfolio",
            "bitcoin-ecosystem",
            "ftx-bankruptcy-estate",
            "2017-2018-alt-season"
        ],
        "max_supply": 21000000,
        "circulating_supply": 19827978,
        "total_supply": 19827978,
        "infinite_supply": false,
        "platform": null,
        "cmc_rank": 1,
        "self_reported_circulating_supply": null,
        "self_reported_market_cap": null,
        "tvl_ratio": null,
        "last_updated": "2025-02-23T08:53:00.000Z",
        "quote": {
            "EUR": {
                "price": 92142.32496837493,
                "volume_24h": 15673715027.990385,
                "volume_change_24h": -65.514,
                "percent_change_1h": -0.17890452,
                "percent_change_24h": 0.24457696,
                "percent_change_7d": -0.83807695,
                "percent_change_30d": -8.64464677,
                "percent_change_60d": -1.56899312,
                "percent_change_90d": -2.00712508,
                "market_cap": 1826995992341.7886,
                "market_cap_dominance": 60.1829,
                "fully_diluted_market_cap": 1934988824335.875,
                "tvl": null,
                "last_updated": "2025-02-23T08:53:03.000Z"
            }
        }
    },
    {
        "id": 1027,
        "name": "Ethereum",
        "symbol": "ETH",
        "slug": "ethereum",
        "num_market_pairs": 9948,
        "date_added": "2015-08-07T00:00:00.000Z",
        "tags": [
            "pos",
            "smart-contracts",
            "ethereum-ecosystem",
            "coinbase-ventures-portfolio",
            "three-arrows-capital-portfolio",
            "polychain-capital-portfolio",
            "heco-ecosystem",
            "binance-labs-portfolio",
            "avalanche-ecosystem",
            "solana-ecosystem",
            "blockchain-capital-portfolio",
            "boostvc-portfolio",
            "cms-holdings-portfolio",
            "dcg-portfolio",
            "dragonfly-capital-portfolio",
            "electric-capital-portfolio",
            "fabric-ventures-portfolio",
            "framework-ventures-portfolio",
            "hashkey-capital-portfolio",
            "kenetic-capital-portfolio",
            "huobi-capital-portfolio",
            "alameda-research-portfolio",
            "a16z-portfolio",
            "1confirmation-portfolio",
            "winklevoss-capital-portfolio",
            "usv-portfolio",
            "placeholder-ventures-portfolio",
            "pantera-capital-portfolio",
            "multicoin-capital-portfolio",
            "paradigm-portfolio",
            "tezos-ecosystem",
            "near-protocol-ecosystem",
            "velas-ecosystem",
            "ethereum-pow-ecosystem",
            "osmosis-ecosystem",
            "layer-1",
            "ftx-bankruptcy-estate",
            "zksync-era-ecosystem",
            "viction-ecosystem",
            "klaytn-ecosystem",
            "sora-ecosystem",
            "rsk-rbtc-ecosystem",
            "starknet-ecosystem",
            "world-liberty-financial-portfolio"
        ],
        "max_supply": null,
        "circulating_supply": 120568910.11267465,
        "total_supply": 120568910.11267465,
        "infinite_supply": true,
        "platform": null,
        "cmc_rank": 2,
        "self_reported_circulating_supply": null,
        "self_reported_market_cap": null,
        "tvl_ratio": null,
        "last_updated": "2025-02-23T08:53:00.000Z",
        "quote": {
            "EUR": {
                "price": 2687.609041962071,
                "volume_24h": 17494448566.559708,
                "volume_change_24h": -42.5212,
                "percent_change_1h": -0.47581382,
                "percent_change_24h": 4.52396493,
                "percent_change_7d": 4.22999986,
                "percent_change_30d": -17.29692539,
                "percent_change_60d": -19.38548885,
                "percent_change_90d": -17.69685705,
                "market_cap": 324042092998.33655,
                "market_cap_dominance": 10.6742,
                "fully_diluted_market_cap": 324042092998.34015,
                "tvl": null,
                "last_updated": "2025-02-23T08:53:03.000Z"
            }
        }
    },
    {
        "id": 52,
        "name": "XRP",
        "symbol": "XRP",
        "slug": "xrp",
        "num_market_pairs": 1541,
        "date_added": "2013-08-04T00:00:00.000Z",
        "tags": [
            "medium-of-exchange",
            "enterprise-solutions",
            "xrp-ecosystem",
            "arrington-xrp-capital-portfolio",
            "galaxy-digital-portfolio",
            "a16z-portfolio",
            "pantera-capital-portfolio",
            "ftx-bankruptcy-estate",
            "2017-2018-alt-season",
            "klaytn-ecosystem",
            "made-in-america"
        ],
        "max_supply": 100000000000,
        "circulating_supply": 57887806032,
        "total_supply": 99986418374,
        "infinite_supply": false,
        "platform": null,
        "cmc_rank": 3,
        "self_reported_circulating_supply": null,
        "self_reported_market_cap": null,
        "tvl_ratio": null,
        "last_updated": "2025-02-23T08:54:00.000Z",
        "quote": {
            "EUR": {
                "price": 2.4757901234002238,
                "volume_24h": 2230440779.131078,
                "volume_change_24h": -59.646,
                "percent_change_1h": -0.04103694,
                "percent_change_24h": 0.66718375,
                "percent_change_7d": -6.5001151,
                "percent_change_30d": -18.40803366,
                "percent_change_60d": 13.19538619,
                "percent_change_90d": 70.34773686,
                "market_cap": 143318058439.3335,
                "market_cap_dominance": 4.721,
                "fully_diluted_market_cap": 247579012340.02097,
                "tvl": null,
                "last_updated": "2025-02-23T08:53:03.000Z"
            }
        }
    },
    {
        "id": 825,
        "name": "Tether USDt",
        "symbol": "USDT",
        "slug": "tether",
        "num_market_pairs": 117672,
        "date_added": "2015-02-25T00:00:00.000Z",
        "tags": [
            "stablecoin",
            "asset-backed-stablecoin",
            "ethereum-ecosystem",
            "waves-ecosystem",
            "bitcoin-cash-ecosystem",
            "heco-ecosystem",
            "algorand-ecosystem",
            "avalanche-ecosystem",
            "solana-ecosystem",
            "polygon-ecosystem",
            "fantom-ecosystem",
            "terra-ecosystem",
            "tezos-ecosystem",
            "near-protocol-ecosystem",
            "arbitrum-ecosystem",
            "celo-ecosystem",
            "iotex-ecosystem",
            "zilliqa-ecosystem",
            "harmony-ecosystem",
            "moonriver-ecosystem",
            "cronos-ecosystem",
            "injective-ecosystem",
            "oasis-ecosystem",
            "moonbeam-ecosystem",
            "usd-stablecoin",
            "xdc-ecosystem",
            "everscale-ecosystem",
            "velas-ecosystem",
            "doge-chain-ecosystem",
            "ethereum-pow-ecosystem",
            "aptos-ecosystem",
            "sui-ecosystem",
            "optimism-ecosystem",
            "canto-ecosystem",
            "osmosis-ecosystem",
            "zksync-era-ecosystem",
            "pulsechain-ecosystem",
            "sei-ecosystem",
            "toncoin-ecosystem",
            "fiat-stablecoin",
            "viction-ecosystem",
            "gnosis-chain-ecosystem",
            "klaytn-ecosystem",
            "okexchain-ecosystem",
            "conflux-ecosystem",
            "kcc-ecosystem",
            "tron20-ecosystem",
            "kardiachain-ecosystem",
            "rsk-rbtc-ecosystem",
            "telos-ecosystem",
            "boba-network-ecosystem",
            "fusion-network-ecosystem",
            "hoo-smart-chain-ecosystem",
            "secret-ecosystem",
            "aurora-ecosystem",
            "metis-andromeda-ecosystem",
            "meter-ecosystem",
            "fuse-ecosystem",
            "syscoin-ecosystem",
            "milkomeda-ecosystem",
            "bitgert-ecosystem",
            "astar-ecosystem",
            "cube-network-ecosystem",
            "thundercore-ecosystem",
            "redlight-chain-ecosystem",
            "core-ecosystem",
            "polygon-zkevm-ecosystem",
            "eos-evm-ecosystem",
            "starknet-ecosystem",
            "mantle-ecosystem",
            "neon-evm-ecosystem",
            "manta-pacific-ecosystem",
            "scroll-ecosystem",
            "x-layer-ecosystem",
            "world-liberty-financial-portfolio"
        ],
        "max_supply": null,
        "circulating_supply": 142489546118.1509,
        "total_supply": 144566824336.9391,
        "platform": {
            "id": 1027,
            "name": "Ethereum",
            "symbol": "ETH",
            "slug": "ethereum",
            "token_address": "0xdac17f958d2ee523a2206206994597c13d831ec7"
        },
        "infinite_supply": true,
        "cmc_rank": 4,
        "self_reported_circulating_supply": null,
        "self_reported_market_cap": null,
        "tvl_ratio": null,
        "last_updated": "2025-02-23T08:53:00.000Z",
        "quote": {
            "EUR": {
                "price": 0.9567241648685417,
                "volume_24h": 53925349017.919174,
                "volume_change_24h": -47.618,
                "percent_change_1h": 0.03878279,
                "percent_change_24h": 0.08293283,
                "percent_change_7d": 0.05688923,
                "percent_change_30d": 0.05541576,
                "percent_change_60d": 0.14321365,
                "percent_change_90d": -0.03026717,
                "market_cap": 136323192012.3855,
                "market_cap_dominance": 4.4906,
                "fully_diluted_market_cap": 138310574281.4544,
                "tvl": null,
                "last_updated": "2025-02-23T08:53:03.000Z"
            }
        }
    },
    {
        "id": 1839,
        "name": "BNB",
        "symbol": "BNB",
        "slug": "bnb",
        "num_market_pairs": 2372,
        "date_added": "2017-07-25T00:00:00.000Z",
        "tags": [
            "marketplace",
            "centralized-exchange",
            "payments",
            "smart-contracts",
            "ethereum-ecosystem",
            "alameda-research-portfolio",
            "multicoin-capital-portfolio",
            "bnb-chain-ecosystem",
            "layer-1",
            "alleged-sec-securities",
            "celsius-bankruptcy-estate"
        ],
        "max_supply": null,
        "circulating_supply": 142476611,
        "total_supply": 142476611,
        "infinite_supply": false,
        "platform": null,
        "cmc_rank": 5,
        "self_reported_circulating_supply": null,
        "self_reported_market_cap": null,
        "tvl_ratio": null,
        "last_updated": "2025-02-23T08:54:00.000Z",
        "quote": {
            "EUR": {
                "price": 635.4941708609044,
                "volume_24h": 1776193458.1995928,
                "volume_change_24h": -5.9885,
                "percent_change_1h": -0.44943002,
                "percent_change_24h": 1.29028908,
                "percent_change_7d": 1.43836896,
                "percent_change_30d": -3.49674077,
                "percent_change_60d": -5.574911,
                "percent_change_90d": -0.85022468,
                "market_cap": 90543055774.51662,
                "market_cap_dominance": 2.9603,
                "fully_diluted_market_cap": 90543055774.52083,
                "tvl": null,
                "last_updated": "2025-02-23T08:53:03.000Z"
            }
        }
    }
]